# Pandas Movie Dataset

### Hello

### We will be analysing the Movies dataset by using the 'pandas' library


#### This is the Dataset of movies from the year 1931 to 2014.

#### Description:There are five colums
               ID
               Name of Movies
               Year (Release)
               Ratings
               Duration (in seconds)
             
#### ( While loading if you get UTF-8 error so convert the file into 'UTF-8' format)
UTF = Unicode Transformation Format.

### Load Data

#### First import the pandas library

In [25]:
# imporitng the pandas package as pd

import pandas as pd

In [62]:
pd.set_option('display.max_columns',None)
Movie =pd.read_csv("movie.txt", header=None, names=[ 'ID','Name_of_Movie','Year','Ratings','Duration' ])

In [3]:
#to see how many rows and columns:

Movie.shape

(49590, 5)

In [63]:
#starting ten records of the dataset:


Movie.head(10)

   ID                   Name_of_Movie  Year  Ratings  Duration
0   1  The Nightmare Before Christmas  1993      3.9    4568.0
1   2                       The Mummy  1932      3.5    4388.0
2   3            Orphans of the Storm  1921      3.2    9062.0
3   4            The Object of Beauty  1991      2.8    6150.0
4   5                      Night Tide  1963      2.8    5126.0
5   6             One Magic Christmas  1985      3.8    5333.0
6   7                Muriel's Wedding  1994      3.5    6323.0
7   8                   Mother's Boys  1994      3.4    5733.0
8   9     Nosferatu: Original Version  1929      3.5    5651.0
9  10                    Nick of Time  1995      3.4    5333.0

In [110]:
# To access only the year column
Movie['Year']

0        1993
1        1932
2        1921
3        1991
4        1963
5        1985
6        1994
7        1994
8        1929
9        1995
10       1919
11       1996
12       1915
13       1978
14       1971
15       1985
16       1935
17       1996
18       1981
19       1971
20       1989
21       1987
22       1994
23       1996
24       1986
25       1986
26       1996
27       1972
28       1994
29       1992
         ...
49560    2014
49561    2013
49562    2013
49563    2013
49564    2013
49565    2013
49566    2013
49567    2013
49568    2013
49569    2013
49570    2013
49571    2013
49572    2013
49573    2013
49574    2013
49575    2013
49576    2013
49577    2013
49578    2013
49579    2012
49580    2009
49581    1996
49582    2013
49583    2012
49584    2013
49585    2013
49586    2013
49587    2010
49588    2010
49589    2010
Name: Year, Length: 49590, dtype: int64

### Q1. Number of Movies Released in a year between 1990 to 2000

In [125]:
# TO FIND THE NUMBER OF MOVIES BETWEEN YEAR 1990 to 2000 =
# year1 is a temporary you can overwrite it.

year1= Movie[(Movie['Year']>=1990) & (Movie['Year']<=2000)]
year1.drop(['ID','Ratings','Duration'],inplace=True, axis=1)
year1.count()

C:\Users\VED\Anaconda3\lib\site-packages\pandas\core\frame.py:3697: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  errors=errors)

Name_of_Movie    7388
Year             7388
dtype: int64

### Q2. To find the number of Movies whose ratings are more than 4.

In [68]:
# Ratings of movies more than 4=

Movie[Movie['Ratings']>4]

,ID,Name_of_Movie,Year,Ratings,Duration
138,139,Pulp Fiction,1994,4.1,9265.0
287,288,Life Is Beautiful,1997,4.2,6973.0
302,303,Mulan: Special Edition,1998,4.2,5270.0
464,465,Forrest Gump,1994,4.3,8525.0
490,491,Braveheart,1995,4.2,10658.0
590,591,White Christmas,1954,4.3,7201.0
672,673,Roman Holiday,1953,4.1,7087.0
689,690,The African Queen,1951,4.1,6312.0
954,955,The Boondock Saints,1999,4.1,6507.0
984,985,Paid in Full,2002,4.1,5883.0
1061,1062,The Pianist,2002,4.1,8945.0
1134,1135,American Me,1992,4.1,7552.0
1285,1286,Pirates of the Caribbean: The Curse of the Bla...,2003,4.1,8586.0
1305,1306,Ken Burns: Jazz,2001,4.1,NaN
1306,1307,Ken Burns: Baseball,1994,4.1,NaN
1328,1329,Lonesome Dove,1989,4.1,NaN
1330,1331,Mr. Bean: The Whole Bean,1990,4.1,NaN
1356,1357,The Life of Birds,1998,4.2,NaN
1359,1360,Ken Burns: The Civil War,1990,4.2,NaN
1363,1364,The Life of Mammals,2002,4.2,NaN
1392,1393,The West Wing: Season 1,1999,4.2,NaN
1411,1412,National Lampoon's Christmas Vacation,1989,4.1,5828.0
1461,1462,Firefly: The Complete Series,2002,4.3,NaN
1594,1595,Freaks and Geeks: The Complete Series,1999,4.4,NaN
1606,1607,The West Wing: Season 2,2000,4.2,NaN
1857,1858,The West Wing: Season 3,2001,4.2,NaN
1933,1934,Fullmetal Alchemist,2003,4.3,NaN
1973,1974,Samurai Champloo,2004,4.4,NaN
1993,1994,The West Wing: Season 5,2003,4.2,NaN
1997,1998,The West Wing: Season 4,2002,4.2,NaN
...,...,...,...,...,...
47952,47953,Beyblade: Metal Fury,2012,4.2,NaN
48205,48206,Cake Boss: Next Great Baker: Season 2,2011,4.1,NaN
48212,48213,Cake Boss: Next Great Baker: Season 1,2010,4.1,NaN
48317,48318,Beyblade: Metal Masters,2011,4.2,NaN
48435,48436,Beyblade: Metal Fury,2012,4.2,NaN
48801,48802,Warren Buffett: Bloomberg Game Changers,2013,4.1,2843.0
48828,48829,Video Game High School,2012,4.2,NaN
48838,48839,Video Game High School: Season 2,2013,4.2,NaN
48845,48846,Gator Boys,2011,4.1,NaN
48849,48850,Video Game High School: Season 1,2012,4.2,NaN
48854,48855,Pit Bulls &#38; Parolees,2009,4.3,NaN
48859,48860,Too Cute!,2011,4.3,NaN
48862,48863,Aziz Ansari: Buried Alive,2013,4.1,4780.0
48866,48867,Alaska: The Last Frontier,2011,4.1,NaN
48874,48875,Brew Masters,2010,4.1,NaN
49025,49026,Cake Boss: Next Great Baker,2010,4.1,NaN
49153,49154,Gator Boys: Season 2,2012,4.1,NaN
49193,49194,Stephen Hawking's Grand Design: Season 2,2012,4.1,NaN
49315,49316,Aziz Ansari: Buried Alive (Trailer),2013,4.1,105.0
49326,49327,Top Gear: Series 19,2013,4.2,NaN
49382,49383,Stephen Hawking's Grand Design,2012,4.1,NaN
49485,49486,Max Steel: Season 1,2013,4.1,NaN
49503,49504,Lilyhammer: Season 2 (Trailer),2013,4.5,106.0
49504,49505,Life With Boys,2011,4.1,NaN
49545,49546,Bo Burnham: what.,2013,4.1,3614.0
49548,49549,Life With Boys: Season 1,2011,4.1,NaN
49553,49554,Max Steel,2013,4.1,NaN
49555,49556,Lilyhammer: Season 1 (Recap),2013,4.2,194.0
49570,49571,The Short Game (Trailer),2013,4.1,156.0
49578,49579,Transformers Prime Beast Hunters: Predacons Ri...,2013,4.2,3950.0

### Q3. TO Find the movies whose ratings are between 2 and 4.

In [122]:
#  Movie (ratings) greater than 2 and less then 4. If you just want the count of the movies with ratings put ".count()"in front of R 
# R is just temporary dataframe you can over-write it.

R= Movie[(Movie['Ratings']>=2) & (Movie['Ratings']<=4)]
R.drop(['ID','Year','Duration'],inplace=True, axis=1)
R

C:\Users\VED\Anaconda3\lib\site-packages\pandas\core\frame.py:3697: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  errors=errors)

                                           Name_of_Movie  Ratings
0                         The Nightmare Before Christmas      3.9
1                                              The Mummy      3.5
2                                   Orphans of the Storm      3.2
3                                   The Object of Beauty      2.8
4                                             Night Tide      2.8
5                                    One Magic Christmas      3.8
6                                       Muriel's Wedding      3.5
7                                          Mother's Boys      3.4
8                            Nosferatu: Original Version      3.5
9                                           Nick of Time      3.4
10                                       Broken Blossoms      3.3
11                                             Big Night      3.6
12                                 The Birth of a Nation      2.9
13                                  The Boys from Brazil      3.6
14                                        Big Doll House      2.9
15                                    The Breakfast Club      4.0
16                             The Bride of Frankenstein      3.7
17                                       Beautiful Girls      3.5
18                                         Bustin' Loose      3.7
19                                          The Beguiled      3.4
20                            Born on the Fourth of July      3.4
21                                        Broadcast News      3.4
22                                  Swimming with Sharks      3.3
23                       Beavis and Butt-head Do America      3.4
24                                Brighton Beach Memoirs      3.4
25                                     The Best of Times      3.4
26                                           Brassed Off      3.5
27                                   Last Tango in Paris      3.1
28                                          Leprechaun 2      3.2
29         Incident at Oglala: The Leonard Peltier Story      3.7
...                                                  ...      ...
49549                                   El Fuente: 30 MP      3.3
49550                                 El Fuente: 2997 MP      3.2
49551                                   El Fuente: 25 MP      3.3
49552                                   El Fuente: 24 MP      3.5
49554                                       Saving Santa      3.8
49556                                       Shinobi Girl      2.0
49557  GLOW: The Story of the Gorgeous Ladies of Wres...      3.7
49558                                     Mitt (Trailer)      3.0
49560                               The Square (Trailer)      3.6
49561                  My Hope America with Billy Graham      3.9
49564                                    American Addict      3.5
49565                  My Hope America with Billy Graham      3.9
49566                               El Fuente: 2997 MP10      2.7
49567                                 El Fuente: 25 MP10      2.9
49568                                 El Fuente: 24 MP10      2.8
49569                              El Fuente: 23976 MP10      2.9
49571                               El Fuente: 5994 MP10      2.8
49572                                 El Fuente: 50 MP10      2.9
49573                                 El Fuente: 30 MP10      2.8
49574                    Greg Fitzsimmons: Life on Stage      3.3
49575                        Dave Foley: Relatively Well      3.2
49579              Underground: The Julian Assange Story      3.7
49580            Curious George: A Very Monkey Christmas      3.8
49581                           Mumfie's White Christmas      2.4
49582   Lady Gaga &#38; The Muppets' Holiday Spectacular      3.1
49583                                       Sunset Strip      3.0
49584                                       Silver Bells      3.5
49585                                  Winter Wonderland      2.8
49588                                    Kate Plus Ei8ht      2.7
49589                          Kate Plus Ei8ht: Season 1      2.7

[9836 rows x 2 columns]

### Q4. Find the number of movies with duration more than 2 hours (7200 second).

In [61]:
# To Find the Movies having duration more than 2hours 7200 seconds
# If you only want the count store it in a variable and print.

Movie[Movie[4] > 7200]

,0,1,2,3,4
2,3,Orphans of the Storm,1921,3.2,9062.0
12,13,The Birth of a Nation,1915,2.9,12118.0
13,14,The Boys from Brazil,1978,3.6,7417.0
20,21,Born on the Fourth of July,1989,3.4,8646.0
21,22,Broadcast News,1987,3.4,7940.0
27,28,Last Tango in Paris,1972,3.1,7732.0
35,36,Into the Woods,1990,4.0,9077.0
38,39,King Kong,1976,3.2,8044.0
41,42,In the Name of the Father,1993,3.9,7972.0
47,48,Emma,1996,3.5,7260.0
49,50,The Eiger Sanction,1975,3.5,7726.0
54,55,The Doors,1991,3.6,8436.0
66,67,The Andromeda Strain,1971,3.6,7861.0
70,71,All About Eve,1950,3.8,8300.0
74,75,Apocalypse Now,1979,4.0,8825.0
79,80,Little Buddha,1993,3.4,8455.0
84,85,The Hunt for Red October,1990,4.0,8106.0
85,86,The Hindenburg,1975,3.4,7546.0
92,93,Heaven's Gate,1980,3.0,13143.0
113,114,Far and Away,1992,3.6,8396.0
128,129,The Falcon and the Snowman,1985,3.4,7891.0
138,139,Pulp Fiction,1994,4.1,9265.0
139,140,Reds,1981,3.5,11710.0
141,142,Passion Fish,1992,3.6,8079.0
144,145,The Piano,1993,3.6,7245.0
151,152,Chitty Chitty Bang Bang,1968,3.6,8730.0
164,165,Clockers,1995,3.4,7699.0
177,178,Rob Roy,1995,3.7,8359.0
188,189,Way Down East,1920,3.0,8985.0
194,195,True Grit,1969,3.9,7681.0
...,...,...,...,...,...
40856,40857,Ajj De Ranjhe,2012,2.9,8636.0
40935,40936,A Werewolf Boy,2012,4.1,7552.0
40979,40980,London: The Modern Babylon,2012,3.2,7672.0
40984,40985,New Hope,2012,4.1,7470.0
41434,41435,Talaash,2012,3.9,8326.0
41574,41575,VGHS: The Movie,2012,3.9,7443.0
42114,42115,Back to 1942,2012,3.6,8780.0
42311,42312,Matru ki Bijlee ka Mandola,2013,3.2,8873.0
42604,42605,Spiritual Revolution,2008,3.7,7446.0
42645,42646,56 Up,2012,4.0,8617.0
42667,42668,Die Nibelungen: Kriemhild's Revenge,1924,3.1,7878.0
42668,42669,Siegfried,1924,3.2,9005.0
42876,42877,The Tower,2012,3.6,7302.0
42988,42989,Molly's Girl,2012,2.7,7354.0
43227,43228,Day of the Falcon,2011,3.8,7810.0
43335,43336,We Steal Secrets: The Story of WikiLeaks,2013,3.9,7787.0
44550,44551,WWE: The Best of Raw &#38; SmackDown 2012: Vol. 2,2012,NaN,8036.0
44551,44552,WWE: The Best of Raw &#38; SmackDown 2012: Vol. 3,2012,NaN,10664.0
44553,44554,WWE: The Best of Raw &#38; SmackDown 2012: Vol. 1,2012,NaN,7773.0
44561,44562,New World,2013,3.9,8113.0
44598,44599,Perlasca,2002,3.9,7455.0
44656,44657,Makers Our Story,2011,1.6,8162.0
45029,45030,Salinger,2013,4.0,7425.0
45075,45076,The Horde,2012,3.0,7776.0
45105,45106,Elephants Dream 4 Hour,2006,3.1,11780.0
45107,45108,Settai,2013,2.8,7390.0
46831,46832,WWE for All Mankind: The Life &#38; Career of ...,2013,4.2,8066.0
46948,46949,Example Short XII 23976 2 Hour,2010,2.6,7370.0
48713,48714,WWE: The Top 25 Rivalries in Wrestling History,2013,3.7,10228.0
49054,49055,Theeya Velai Seyyanum Kumaru,2013,3.3,8239.0

## For checking the Null values

In [96]:
# "isnull()" is used to checkthe null vlues.

Movie.isnull()

          ID  Name_of_Movie   Year  Ratings  Duration
0      False          False  False    False     False
1      False          False  False    False     False
2      False          False  False    False     False
3      False          False  False    False     False
4      False          False  False    False     False
5      False          False  False    False     False
6      False          False  False    False     False
7      False          False  False    False     False
8      False          False  False    False     False
9      False          False  False    False     False
10     False          False  False    False     False
11     False          False  False    False     False
12     False          False  False    False     False
13     False          False  False    False     False
14     False          False  False    False     False
15     False          False  False    False     False
16     False          False  False    False     False
17     False          False  False    False     False
18     False          False  False    False     False
19     False          False  False    False     False
20     False          False  False    False     False
21     False          False  False    False     False
22     False          False  False    False     False
23     False          False  False    False     False
24     False          False  False    False     False
25     False          False  False    False     False
26     False          False  False    False     False
27     False          False  False    False     False
28     False          False  False    False     False
29     False          False  False    False     False
...      ...            ...    ...      ...       ...
49560  False          False  False    False     False
49561  False          False  False    False      True
49562  False          False  False     True     False
49563  False          False  False     True     False
49564  False          False  False    False     False
49565  False          False  False    False      True
49566  False          False  False    False     False
49567  False          False  False    False     False
49568  False          False  False    False     False
49569  False          False  False    False     False
49570  False          False  False    False     False
49571  False          False  False    False     False
49572  False          False  False    False     False
49573  False          False  False    False     False
49574  False          False  False    False     False
49575  False          False  False    False     False
49576  False          False  False     True     False
49577  False          False  False     True     False
49578  False          False  False    False     False
49579  False          False  False    False     False
49580  False          False  False    False     False
49581  False          False  False    False     False
49582  False          False  False    False     False
49583  False          False  False    False     False
49584  False          False  False    False     False
49585  False          False  False    False     False
49586  False          False  False     True     False
49587  False          False  False     True     False
49588  False          False  False    False      True
49589  False          False  False    False      True

[49590 rows x 5 columns]

In [111]:
# There are some NUll values in the dataset:
# Counting the total number of null values present in the dataset. 'sum' is for the total count.

print("These are the total count of NULL values present")

Movie.isnull().sum()

These are the total count of NULL values present

ID                   0
Name_of_Movie        0
Year                 0
Ratings          38776
Duration          3754
dtype: int64

## Finished